variable "filename" {
        default = "/home/ubuntu/terraform-course/terraform-variables/devops-automated.txt"
}

variable "content" {
        default = "This is autogenerated from variables "
}

variable "devops_op_trainer" {}

variable "content_map" {
type = map
default =  {
"content1" = "this is content 1"
"content2" = "this is cooler content 2 "
}
}


variable "file_list" {
type = list
default = ["/home/ubuntu/terraform-course/terraform-variables/files_1.txt","/home/ubuntu/terraform-course/terraform-variables/files_2.txt"]
}

variable "aws_ec2_object" {
        type = object ({
                        name = string
                        instances  = number
                        keys = list(string)
                        ami = string
                        })

        default = { 
                name = "test_ec2_instance"
                instances = 4
                keys = ["key1.pem","key2.pem"]
                ami = "this is another string defined under ami"
}
}
variable "no_of_students" {}


